// Generated by CoffeeScript 1.9.1

/**
 * Created by awaln on 4/15/15.
 */

(function() {
  this.compile = function(convert_to, drawing) {
    var code, edge, headers, i, j, k, l, len, len1, len2, len3, name, node, ref, ref1, ref2, ref3, relation, relations;
    if (convert_to === 'LaTeX') {
      headers = '\\usepackage{tikz}\n';
      code = '\\begin{tikzpicture}[scale = 1]\n';
      ref = drawing['edges'];
      for (i = 0, len = ref.length; i < len; i++) {
        edge = ref[i];
        relations = {
          start: [],
          end: []
        };
        ref1 = Object.keys(drawing['nodes']);
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          name = ref1[j];
          node = drawing.nodes[name];
          if (node.type === 'circle' && distance_formula(node.center_x, node.center_y, edge['start'][0], edge['start'][1]) < node.radius) {
            relations['start'].push(node.name);
          }
          if (node.type === 'circle' && distance_formula(node.center_x, node.center_y, edge['end'][0], edge['end'][1]) < node.radius) {
            relations['end'].push(node.name);
          }
        }
        if (relations['start'].length > 0 && relations['end'].length > 0) {
          relations['name'] = "Edge " + drawing['relations'].length;
          drawing['relations'].push(relations);
        }
      }
      ref2 = Object.keys(drawing.nodes);
      for (k = 0, len2 = ref2.length; k < len2; k++) {
        name = ref2[k];
        node = drawing.nodes[name];
        code += '\\node[style=circle,draw, minimum size = ' + node.radius + 'pt] (' + node.name + ') at (' + node.center_x + 'pt, -' + node.center_y + 'pt) {' + node.name + '};\n';
      }
      code += "\\path\n";
      ref3 = drawing.relations;
      for (l = 0, len3 = ref3.length; l < len3; l++) {
        relation = ref3[l];
        code += '(' + relation.start[0] + ') edge node {' + relation.name + '} (' + relation.end[0] + ')\n';
      }
      code += ";";
      document.getElementById('tex_includes').value = headers;
      code += '\\end{tikzpicture}\n';
      document.getElementById('tex_tex').value = code;
    }
  };

}).call(this);
