###*
# Created by awaln on 4/15/15.
###

# converts drawing from an object with items to TikZ latex.

@compile = (convert_to, drawing) ->
  # if LaTeX, make it
  if convert_to == 'LaTeX'
    headers = '\\usepackage{tikz}\n'
    code = '\\begin{tikzpicture}[scale = 1]\n'

    # look at the loners first, relate to nodes if possible
    for loner, i in drawing['loners']
      relations = {start:[], end:[]}
      for name in Object.keys(drawing['nodes'])
        node = drawing.nodes[name]
        # check for start node overlap
        if node.type == 'circle' and distance_formula(node.center_x, node.center_y, loner['start'][0], loner['start'][1]) < node.radius
          relations['start'].push(node.name)
        if node.type == 'circle' and distance_formula(node.center_x, node.center_y, loner['end'][0], loner['end'][1]) < node.radius
          relations['end'].push(node.name)
      if relations['start'].length > 0 and relations['end'].length > 0
        drawing.loners.splice(i, 1)
        for s in relations.start
          if not drawing.edges[s]
            drawing.edges[s] = []
          for t in relations.end
            if t not in drawing.edges[s]
              drawing.edges[s].push t
              drawing.edgelabels[s + " " + t] = "Edge " + Object.keys(drawing.edgelabels).length

    # TODO: Study relations and decide on a template to use

    # place nodes
    for name in Object.keys(drawing.nodes)
      node = drawing.nodes[name]
      code += '\\node[style=circle,draw, minimum size = ' + node.radius + 'pt] (' + node.name + ') at (' + node.center_x + 'pt, -' + node.center_y + 'pt) {' + node.name + '};\n'

    # place edges
    code += "\\path\n"
    for s in Object.keys drawing.edges
      for e in drawing.edges[s]
        code += '(' + s + ') edge node {'+ drawing.edgelabels[s + " " + e] + '} (' + e + ')\n'
    code += ";"

    # add necessary headers
    document.getElementById('tex_includes').value = headers
    # add code
    code += '\\end{tikzpicture}\n'
    document.getElementById('tex_tex').value = code
  return

# ---
# generated by js2coffee 2.0.3